version: '3.8'

services:
  database:
    container_name: database
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Supersnak3
      MYSQL_DATABASE: motospots
      MYSQL_USER: api_user
      MYSQL_PASSWORD: Supersnak3
    ports:
      - '4306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/usr/src/app/motospots.com
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: library/nginx:stable-alpine
    ports:
      - '8080:80'
#      - '443:443'
    volumes:
      - ../:/usr/src/app/motospots.com
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
    depends_on:
      - php
      - database

networks:
  docker-network:
    driver: bridge

volumes:
  mysql_data: