version: '3.8'

services:
  database:
    container_name: database
    image: mariadb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Supersnak3
      MYSQL_DATABASE: motospots
      MYSQL_USER: api_user
      MYSQL_PASSWORD: Supersnak3
    ports:
      - '4306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php
    restart: unless-stopped
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/usr/src/app/motospots.com
      - ~/private/var/log/motospots:/usr/src/app/motospots.com/var/log
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: library/nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ../:/usr/src/app/motospots.com
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/src/app/certbot
      - ./dhparam/dhparam:/etc/ssl/certs
    depends_on:
      - php
      - database

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/src/app/certbot --email jtsmrdel@gmail.com --agree-tos --no-eff-email -d motospots.com -d www.motospots.com
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/src/app/certbot

  sumologic:
    image: sumologic/collector:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
    environment:
      SUMO_ACCESS_ID: suKqP7jrUEySH5
      SUMO_ACCESS_KEY: yeWjWYotWfW8A38aJVnvcuZHF0q2796nZ6XTF4pn52ll9VTDkIZG3cIATJs131xY

volumes:
  mysql_data:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: Documents/Personal/Software\ Development/motospots.nosync/docker/dhparam/
      o: bind